<Wid_Alfa>:
    orientation: 'vertical'
    canvas:
        Color:
            rgb: 1,1,1
        Rectangle:
            size: self.size
            pos: self.pos

<Wid_Box1>:
    size_hint: 1,.1
    canvas:
        Color:
            rgb: 1,0,0
        Rectangle:
            size: self.size
            pos: self.pos

<Wid_Box2>:
    size_hint: 1,.9
    canvas:
        Color:
            rgb: 0,0,1
        Rectangle:
            size: self.size
            pos: self.pos
