<MyWidget>:
    orientation: 'vertical'
    FloatLayout:
        id: wid1
        size_hint: 1,.9
        Widget:
            id: bar
            pos_hint: {'x': 0.5, 'y': 0.5}
            size_hint: 0, None
            height: 150     
            animated_color: (1, 0, 0)
            canvas:
                Color:
                    rgb: self.animated_color
                Rectangle:
                    size: self.size
                    pos: self.pos
                    
    BoxLayout:
        size_hint: 1,.1
        Button:
            text: "start"
            size: self.size
            pos: self.pos
            on_release: root.animate_it(self)